name: resume-analyzer

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - resume_analyzer_network

  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_vol:/data/db
    networks:
      - resume_analyzer_network

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - shared_data:/shared
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - resume_analyzer_network

  worker:
    build: ./worker
    container_name: worker
    env_file:
      - .env
    volumes:
      - shared_data:/shared
    depends_on:
      - mongo
      - rabbitmq
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - resume_analyzer_network

  ollama:
    container_name: ollama
    build: ./ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_vol:/ollama
    entrypoint: ["/usr/bin/bash", "pull-llama3.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - resume_analyzer_network

volumes:
  mongo_vol:
  ollama_vol:
  shared_data:

networks:
  resume_analyzer_network:
    driver: bridge
