name: resume-analyzer

services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_vol:/data/db

  ollama:
    container_name: ollama
    build: ./ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_vol:/ollama
    entrypoint: ["/usr/bin/bash", "pull-llama3.sh"]

volumes:
  mongo_vol:
  ollama_vol:
